@host=http://localhost:5062
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDFkMDc3YS03YTFjLTQ2ZWItYTEwMS0yMjVhOTVhOGNiMTIiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNjQ3YzE0MzgtMTBhNC00NzdhLTgwYWMtZTk5MmY0MDIxZDNjIiwiZXhwIjoxNzA2OTMwMTgxLCJpc3MiOiJCdWJlckRpbm5lciJ9.shVKJB33Pb_uMg9tLmUjGG9NQe1CWxW_6wAkhyPAz6Y